print ("Welcome to the mad libs game!")
Name = input("Please enter your name: ")
Age = input("Please enter your age: ")
Food = input("Please enter the name of your favourite food: ")
Body_part = input("Please enter the name of a body part: ")
Adj1 = input("Please enter an adjective: ")
Adj2 = input("Please enter another adjective: ")
Disease = input("Please enter the name of a deadly disease: ")
Verb = input("Please enter a verb in the past tense : ")
print ("There once was a person named " + Name + ".")
print ("He was " + Age + " years old.")
print ("His " + Body_part.lower() + " was really big and he was really " + Adj1.lower() + ".")
print ("One day, he decided that he wanted to eat some " + Food.lower() + ".")
print ("So, he decided to go the store.")
print ("He was very " + Adj2.lower() + " because everything was free in the store that day.")
print ("So, he ate so much that he had " + Disease.lower() + ".")
print ("From that, he " + Verb.lower() + " a lesson to not eat that much " + Food.lower() + " again.")
print ("Thank you for playing!")